-- V018: Seed widget_type_catalog with all 28 chart types from RENDER_CONTRACTS.md v7.0.
-- Categories: visualization (13), filter (4), layout (2), healthcare (12), ai (1) = 32 total entries.
-- sort_order groups by category for Dashboard Designer palette display.

INSERT INTO widget_type_catalog
    (chart_type, category, label, description, icon, required_columns, optional_columns, compatible_with, sort_order)
VALUES

-- ── Visualization (1–13) ──────────────────────────────────────────────────────

('line_chart', 'visualization', 'Biểu đồ đường',
 'Xu hướng theo thời gian hoặc danh mục. Hỗ trợ nhiều series.',
 'TrendingUp',
 ARRAY['x', 'y'],
 ARRAY['series', 'color', 'annotations'],
 ARRAY['bar_chart', 'area_chart'],
 10),

('bar_chart', 'visualization', 'Biểu đồ cột',
 'So sánh giá trị giữa các danh mục. Hỗ trợ ngang/dọc và nhiều series.',
 'BarChart2',
 ARRAY['x', 'y'],
 ARRAY['series', 'color'],
 ARRAY['line_chart', 'area_chart'],
 11),

('area_chart', 'visualization', 'Biểu đồ vùng',
 'Xu hướng với phần tô màu bên dưới đường. Tốt cho dữ liệu tích lũy.',
 'AreaChart',
 ARRAY['x', 'y'],
 ARRAY['series', 'color'],
 ARRAY['line_chart', 'bar_chart'],
 12),

('pie_chart', 'visualization', 'Biểu đồ tròn',
 'Tỷ lệ phần trăm thành phần. Tối đa 8 lát cắt khuyến nghị.',
 'PieChart',
 ARRAY['label', 'value'],
 ARRAY['color'],
 ARRAY['donut_chart'],
 13),

('donut_chart', 'visualization', 'Biểu đồ vòng',
 'Tỷ lệ phần trăm với lỗ trống ở giữa để hiển thị tổng.',
 'Donut',
 ARRAY['label', 'value'],
 ARRAY['color'],
 ARRAY['pie_chart'],
 14),

('kpi', 'visualization', 'KPI đơn',
 'Một chỉ số chính với so sánh và sparkline.',
 'Hash',
 ARRAY['value', 'label'],
 ARRAY['deltaPercent', 'direction', 'sparkline', 'format'],
 ARRAY['kpi_grid'],
 15),

('gauge', 'visualization', 'Đồng hồ đo',
 'Chỉ số dạng kim đồng hồ với ngưỡng màu sắc.',
 'Gauge',
 ARRAY['value', 'min', 'max'],
 ARRAY['unit', 'target', 'thresholds'],
 ARRAY[],
 16),

('heatmap', 'visualization', 'Bản đồ nhiệt',
 'Dữ liệu hai chiều được tô màu theo cường độ.',
 'Grid',
 ARRAY['x', 'y', 'value'],
 ARRAY['tooltip'],
 ARRAY[],
 17),

('scatter', 'visualization', 'Biểu đồ phân tán',
 'Phân tán điểm dữ liệu trên trục X/Y. Hỗ trợ bubble chart.',
 'ScatterChart',
 ARRAY['x', 'y'],
 ARRAY['size', 'label', 'series', 'color'],
 ARRAY[],
 18),

('advanced_table', 'visualization', 'Bảng nâng cao',
 'Bảng phân trang phía server, sort, filter, export CSV/Excel.',
 'Table',
 ARRAY[],
 ARRAY[],
 ARRAY['simple_table'],
 19),

('simple_table', 'visualization', 'Bảng đơn giản',
 'Bảng phân trang phía client. Tối đa 1000 dòng.',
 'List',
 ARRAY[],
 ARRAY[],
 ARRAY['advanced_table'],
 20),

('pivot_table', 'visualization', 'Bảng pivot',
 'Cross-tabulation nhiều chiều với tổng hàng/cột.',
 'LayoutGrid',
 ARRAY[],
 ARRAY[],
 ARRAY[],
 21),

('funnel', 'visualization', 'Biểu đồ phễu',
 'Tỷ lệ chuyển đổi qua các bước (conversion funnel).',
 'Filter',
 ARRAY['label', 'value'],
 ARRAY['percentOfStart', 'dropRate'],
 ARRAY['patient_flow_stages'],
 22),

-- ── Filter (14–17) ────────────────────────────────────────────────────────────

('filter_dropdown', 'filter', 'Bộ lọc danh sách',
 'Dropdown chọn một hoặc nhiều giá trị để lọc dashboard.',
 'ChevronDown',
 ARRAY['filterKey', 'options'],
 ARRAY['currentValue', 'multiSelect'],
 ARRAY[],
 30),

('filter_date_range', 'filter', 'Bộ lọc ngày',
 'Chọn khoảng thời gian với preset (hôm nay, tháng này, v.v.).',
 'Calendar',
 ARRAY['filterKey'],
 ARRAY['presets', 'minDate', 'maxDate'],
 ARRAY[],
 31),

('filter_slider', 'filter', 'Bộ lọc số',
 'Thanh kéo chọn khoảng giá trị số.',
 'Sliders',
 ARRAY['filterKey', 'min', 'max'],
 ARRAY['step', 'format'],
 ARRAY[],
 32),

('filter_search', 'filter', 'Ô tìm kiếm',
 'Full-text search với debounce 500ms.',
 'Search',
 ARRAY['filterKey'],
 ARRAY['placeholder'],
 ARRAY[],
 33),

-- ── Layout (18–19) ────────────────────────────────────────────────────────────

('text_widget', 'layout', 'Văn bản / Markdown',
 'Hiển thị nội dung markdown với template variable substitution.',
 'FileText',
 ARRAY['content'],
 ARRAY['renderMode', 'templateVariables'],
 ARRAY[],
 40),

('tab_container', 'layout', 'Tab container',
 'Nhóm các widget theo tab. Widget trong tab không-mặc định được lazy load.',
 'Tabs',
 ARRAY['tabs'],
 ARRAY[],
 ARRAY[],
 41),

-- ── Healthcare (20–31) ────────────────────────────────────────────────────────

('kpi_grid', 'healthcare', 'Lưới KPI',
 'Lưới 2–5 cột các KPI card. Dùng cho overview đầu trang.',
 'LayoutDashboard',
 ARRAY['id', 'label', 'value'],
 ARRAY['format', 'deltaPercent', 'direction', 'sparkline', 'icon', 'variant'],
 ARRAY['kpi'],
 50),

('progress_rows', 'healthcare', 'Thanh tiến trình',
 'Hàng thanh progress có nhãn. Dùng cho công suất giường, OR.',
 'Activity',
 ARRAY['id', 'label', 'current', 'max'],
 ARRAY['sublabel', 'percent', 'colorThresholds', 'badge', 'badgeVariant'],
 ARRAY[],
 51),

('flow_steps', 'healthcare', 'Luồng bước',
 'Bước điều trị ngang/dọc. Dùng cho quy trình chăm sóc bệnh nhân.',
 'ArrowRight',
 ARRAY['id', 'label', 'status'],
 ARRAY['sublabel', 'count'],
 ARRAY[],
 52),

('timeline_vertical', 'healthcare', 'Timeline dọc',
 'Dòng thời gian sự kiện theo chiều dọc. Dùng cho lịch sử bệnh nhân.',
 'Clock',
 ARRAY['id', 'timeLabel', 'title', 'status'],
 ARRAY['subtitle', 'actor', 'note', 'isoTime'],
 ARRAY[],
 53),

('alert_list', 'healthcare', 'Danh sách cảnh báo',
 'Feed cảnh báo L1/L2/L3 real-time. Dùng cho cảnh báo lâm sàng.',
 'AlertTriangle',
 ARRAY['id', 'level', 'title', 'time', 'acknowledged'],
 ARRAY['subtitle', 'runbookId', 'acknowledgedBy'],
 ARRAY[],
 54),

('bed_grid', 'healthcare', 'Lưới giường bệnh',
 'Bản đồ giường theo khoa màu sắc. Dùng cho quản lý giường toàn viện.',
 'BedDouble',
 ARRAY['deptId', 'deptName', 'bedId', 'bedLabel', 'status'],
 ARRAY['floor', 'patientId', 'patientName', 'admittedAt'],
 ARRAY[],
 55),

('room_status_grid', 'healthcare', 'Trạng thái phòng',
 'Lưới phòng mổ / ICU với tiến trình và thời gian. Dùng cho quản lý OR.',
 'DoorOpen',
 ARRAY['id', 'label', 'status', 'primaryText'],
 ARRAY['secondaryText', 'progressPercent', 'startTime', 'estimatedEnd', 'badgeLabel'],
 ARRAY[],
 56),

('map_pins', 'healthcare', 'Bản đồ ghim vị trí',
 'Ghim vị trí tuyệt đối trên sơ đồ tầng / bản đồ thành phố.',
 'MapPin',
 ARRAY['id', 'x', 'y', 'label', 'status'],
 ARRAY['sublabel', 'type', 'metadata'],
 ARRAY[],
 57),

('patient_flow_stages', 'healthcare', 'Luồng bệnh nhân',
 'Số bệnh nhân tại mỗi giai đoạn cấp cứu. Dùng cho ER flow.',
 'Users',
 ARRAY['id', 'label', 'count'],
 ARRAY['avgWaitMin', 'status', 'icon'],
 ARRAY['funnel'],
 58),

('risk_tiers', 'healthcare', 'Phân tầng nguy cơ',
 '4 tầng nguy cơ bệnh nhân. Dùng cho quản lý sức khỏe dân số.',
 'ShieldAlert',
 ARRAY['level', 'label', 'count', 'percent', 'color'],
 ARRAY['action', 'changeFromPrev'],
 ARRAY[],
 59),

('news2_bars', 'healthcare', 'NEWS2 Score',
 'Điểm NEWS2 từng bệnh nhân với màu sắc L1/L2/L3.',
 'HeartPulse',
 ARRAY['id', 'name', 'score', 'level'],
 ARRAY['ward', 'bed', 'trend', 'components', 'lastAssessed', 'alertSent'],
 ARRAY[],
 60),

-- ── AI (32) ───────────────────────────────────────────────────────────────────

('chat_panel', 'ai', 'AI Chatbot',
 'Trợ lý AI nhúng vào dashboard. Kết nối với operation AI.',
 'MessageSquare',
 ARRAY[],
 ARRAY['systemRole', 'operationPattern', 'quickQuestions', 'allowedRoles'],
 ARRAY[],
 70)
ON CONFLICT (chart_type) DO NOTHING;
