namespace ReportingPlatform.Transformers.Serialization;

[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(TimeSeriesData))]
[JsonSerializable(typeof(PieData))]
[JsonSerializable(typeof(KpiData))]
[JsonSerializable(typeof(GaugeData))]
[JsonSerializable(typeof(HeatmapData))]
[JsonSerializable(typeof(ScatterData))]
[JsonSerializable(typeof(FunnelData))]
[JsonSerializable(typeof(SimpleTableData))]
[JsonSerializable(typeof(AdvancedTableData))]
[JsonSerializable(typeof(PivotTableData))]
[JsonSerializable(typeof(FilterDropdownData))]
[JsonSerializable(typeof(FilterDateRangeData))]
[JsonSerializable(typeof(FilterSliderData))]
[JsonSerializable(typeof(FilterSearchData))]
[JsonSerializable(typeof(TextWidgetData))]
[JsonSerializable(typeof(TabContainerData))]
// Nested types used by the above records
[JsonSerializable(typeof(ChartSeries))]
[JsonSerializable(typeof(ChartAxes))]
[JsonSerializable(typeof(AxisDefinition))]
[JsonSerializable(typeof(SeriesPoint))]
[JsonSerializable(typeof(ChartAnnotation))]
[JsonSerializable(typeof(PieSlice))]
[JsonSerializable(typeof(GaugeThreshold))]
[JsonSerializable(typeof(HeatmapCell))]
[JsonSerializable(typeof(HeatmapValueRange))]
[JsonSerializable(typeof(ScatterSeries))]
[JsonSerializable(typeof(ScatterPoint))]
[JsonSerializable(typeof(FunnelStep))]
[JsonSerializable(typeof(TableColumn))]
[JsonSerializable(typeof(TablePagination))]
[JsonSerializable(typeof(TableSortSpec))]
[JsonSerializable(typeof(TableAppliedFilter))]
[JsonSerializable(typeof(TableFooter))]
[JsonSerializable(typeof(PivotDimension))]
[JsonSerializable(typeof(PivotMeasure))]
[JsonSerializable(typeof(PivotCell))]
[JsonSerializable(typeof(FilterOption))]
[JsonSerializable(typeof(DateRangeValue))]
[JsonSerializable(typeof(DatePreset))]
[JsonSerializable(typeof(TabDefinition))]
[JsonSerializable(typeof(KpiComparison))]
[JsonSerializable(typeof(IReadOnlyDictionary<string, JsonElement>))]
[JsonSerializable(typeof(IReadOnlyDictionary<string, double?>))]
[JsonSerializable(typeof(IReadOnlyDictionary<string, double>))]
[JsonSerializable(typeof(IReadOnlyList<string>))]
public sealed partial class TransformersJsonContext : JsonSerializerContext;
